"""add academic structure

Revision ID: ab73a69ad2f7
Revises: c711141acce9
Create Date: 2026-08-11 21:42:04.013539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab73a69ad2f7'
down_revision: Union[str, Sequence[str], None] = 'c711141acce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_years_name'), ['name'], unique=True)

    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'course_id', 'number', name='uq_semester_year_course_number')
    )
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semesters_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semesters_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semesters_id'), ['id'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_semester_id'), ['semester_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_semester_id'), ['semester_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admission_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_semester_id'), ['semester_id'], unique=False)
        batch_op.create_foreign_key('fk_students_academic_year_id', 'academic_years', ['academic_year_id'], ['id'])
        batch_op.create_foreign_key('fk_students_semester_id', 'semesters', ['semester_id'], ['id'])
        batch_op.create_foreign_key('fk_students_batch_id', 'batches', ['batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_academic_year_id', type_='foreignkey')
        batch_op.drop_constraint('fk_students_semester_id', type_='foreignkey')
        batch_op.drop_constraint('fk_students_batch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_semester_id'))
        batch_op.drop_index(batch_op.f('ix_students_batch_id'))
        batch_op.drop_index(batch_op.f('ix_students_academic_year_id'))
        batch_op.drop_column('admission_date')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('semester_id')
        batch_op.drop_column('academic_year_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_semester_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_course_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_semester_id'))
        batch_op.drop_index(batch_op.f('ix_batches_name'))
        batch_op.drop_index(batch_op.f('ix_batches_id'))
        batch_op.drop_index(batch_op.f('ix_batches_course_id'))
        batch_op.drop_index(batch_op.f('ix_batches_academic_year_id'))

    op.drop_table('batches')
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semesters_id'))
        batch_op.drop_index(batch_op.f('ix_semesters_course_id'))
        batch_op.drop_index(batch_op.f('ix_semesters_academic_year_id'))

    op.drop_table('semesters')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_name'))
        batch_op.drop_index(batch_op.f('ix_academic_years_id'))

    op.drop_table('academic_years')
    # ### end Alembic commands ###
