"""add attendance sessions

Revision ID: ac5f3a2b8c1d
Revises: ab73a69ad2f7
Create Date: 2026-08-11 22:42:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5f3a2b8c1d'
down_revision: Union[str, Sequence[str], None] = 'ab73a69ad2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attendance_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('semester_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('session_name', sa.String(length=100), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_sessions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_subject_id'), ['subject_id'], unique=False)

    # Add attendance_session_id to attendances
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendances_attendance_session_id'), ['attendance_session_id'], unique=False)
        batch_op.create_foreign_key('fk_attendances_attendance_session_id', 'attendance_sessions', ['attendance_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendances_attendance_session_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attendances_attendance_session_id'))
        batch_op.drop_column('attendance_session_id')

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_semester_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_course_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_batch_id'))

    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###